### ISSUE TITLE
dependency: hex-literal fails to build

### ISSUE THREAD

**Issue by bddap** [shawntabrizi/substrate-package#9]
```
cd substrate-node-template
./scripts/build.sh
```

results in

```
error: proc-macro derive panicked
  --> /Users/a/.cargo/registry/src/github.com-1ecc6299db9ec823/hex-literal-0.1.3/src/lib.rs:38:1
   |
38 | / proc_macro_expr_decl! {
39 | |     /// Macro for converting hex string to byte array at compile time
40 | |     hex! => hex_impl
41 | | }
   | |_^
   |
   = help: message: assertion failed: `(left == right)`
             left: `Some("#[allow(unused,")`,
            right: `Some("#[allow(unused")`
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by bddap** [comment]
hex-literal 0.1.3 is the offending version. Updating to 0.1.4 remedies the issue.

Simply updating `./substrate-node-template/runtime/Cargo.lock` fixes things by letting hex-literal update to 0.1.4.

```
cd substrate-node-template
rm runtime/Cargo.lock
./scripts/build.sh
```

**Comment by soc1c** [comment]
getting the same, bumping hex-literal to 0.1.4 works for me too. thanks @bddap

**Comment by soc1c** [comment]
ref https://github.com/paritytech/substrate/issues/3134

**Comment by kaichaosun** [comment]
If using `substrate-node-new` command to create new node, delete `runtime/wasm/Cargo.lock`, then rebuild with `./scripts/build.sh` can fix this issue.

**Comment by shawntabrizi** [comment]
@kaichaosun So we should update the v1.0 branch of substrate with fix then?

**Comment by kaichaosun** [comment]
There are a few options in mind, and I noticed a few discussions in the document channel:

**Option 1**: Update the v1.0 of Substrate as you mentioned, but the `substrate-up` actually uses this link to download template node, needs to figure out what's the process to release & test the change:
http://releases.parity.io/substrate/x86_64-debian:stretch/latest-v1.0/substrate-node-template.tar.gz

**Option 2**: Use `substrate-package` as a standard way to create template node

**Option 3**: Keep using `substrate-up` scripts, but move [node-template](https://github.com/paritytech/substrate/tree/master/node-template) out of substrate codebase and have its own release process.

FYI: Option 1 is still the default option during my current work, there's a plan to update v1.0 of Substrate after knowing enough about the release process. @shawntabrizi

**Comment by shawntabrizi** [comment]
http://releases.parity.io/substrate/x86_64-debian:stretch/latest-v1.0/substrate-node-template.tar.gz

This file is generated when the v1.0 branch is updated.
